# Generated by Django 5.0.4 on 2024-05-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantprice',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
